import { readFile } from 'node:fs/promises'
import path from 'node:path'
import { describe, expect, it } from 'vitest'

const root = path.resolve(import.meta.dirname, '..')

describe('public website replacement', () => {
  it('is a standalone Project Lens prototype page', async () => {
    const html = await readFile(path.join(root, 'index.html'), 'utf8')
    expect(html).toContain('See the system')
    expect(html).toContain('Project Lens turns unfamiliar repositories')
    expect(html).toContain('Complete Guide')
    expect(html).not.toContain('open-design-ui-prototype')
    expect(html).not.toContain('D:\\hackathon-project')
  })

  it('keeps required public sections and no old media dependency', async () => {
    const html = await readFile(path.join(root, 'index.html'), 'utf8')
    expect(html).toContain('Evidence first')
    expect(html).toContain('Built with Codex')
    expect(html).toContain('Local-first limits')
    expect(html).not.toContain('project-lens-sea.mp4')
  })

  it('keeps the demo placeholder honest and configurable', async () => {
    const html = await readFile(path.join(root, 'index.html'), 'utf8')
    const config = await readFile(path.join(root, 'vite.config.ts'), 'utf8')
    expect(html).toContain('See Project Lens in action')
    expect(html).toContain('demo-placeholder')
    expect(html).toContain('preload=\'metadata\'')
    expect(config).toContain('VITE_DEMO_VIDEO_URL')
    expect(config).toContain('project-lens-demo.mp4')
  })

  it('documents zero-code local demo-video replacement', async () => {
    const readme = await readFile(path.join(root, 'README.md'), 'utf8')
    expect(readme).toContain('website/public/media/project-lens-demo.mp4')
    expect(readme).toContain('website/public/media/project-lens-demo-poster.webp')
    expect(readme).toContain('No source-code changes are required.')
  })

  it('keeps both GitHub actions clickable above the terrain', async () => {
    const html = await readFile(path.join(root, 'index.html'), 'utf8')
    expect((html.match(/href="https:\/\/github\.com\/catDkiller\/project-lens"/g) ?? []).length).toBe(1)
    expect(html).toContain(".mini a[href^=\"https://github.com/\"]")
    expect(html).toContain("link.dataset.terrainInteractionIgnore=''")
    expect(html).toContain("link.rel='noopener noreferrer'")
  })

  it('publishes a sanitized preserved report route', async () => {
    const route = await readFile(path.join(root, 'public', 'report', 'index.html'), 'utf8')
    const overview = await readFile(path.join(root, 'public', 'report', 'overview.md'), 'utf8')
    const guide = await readFile(path.join(root, 'public', 'report', 'complete-guide.md'), 'utf8')
    expect(route).toContain('Generated by Project Lens from the prepared sample project.')
    expect(route).toContain('This preserved example demonstrates Project Lens output.')
    expect(route).toContain('Back to Project Lens')
    expect(route).toContain('View source on GitHub')
    expect(route).toContain('scroll-margin-top')
    expect(overview).toContain('<!-- project-lens:overview:v2 -->')
    expect(guide).toContain('<!-- project-lens:complete-guide:v2 -->')
    for (const text of [route, overview, guide]) {
      expect(text).not.toMatch(/[A-Z]:\\Users\\|\.project-lens|open-design-ui-prototype|eda0a117-322e-4137-a817-e4e2bc32c819|codexThreadId|selectedFolder/)
    }
  })

  it('links the terrain showcase to the report without inventing live analysis', async () => {
    const html = await readFile(path.join(root, 'index.html'), 'utf8')
    expect(html).toContain('Explore a generated report')
    expect(html).toContain('href="/report/"')
    expect(html).toContain('data-terrain-interaction-ignore')
    expect(html).not.toContain('Analyse project')
  })

  it('normalizes wheel input without section-index snapping', async () => {
    const html = await readFile(path.join(root, 'index.html'), 'utf8')
    expect(html).toContain('deltaMode===1')
    expect(html).toContain('deltaMode===2')
    expect(html).toContain('INPUT.wheelWindowMs')
    expect(html).toContain('INPUT.maxVelocity')
    expect(html).not.toContain('go(clamp(closest()+direction,0,N-1))')
  })
})
