import { useCallback, useEffect, useRef, useState } from 'react'
import type { AnalysisEventDto, AnalysisRunStatusDto, CodexStatusDto, RuntimeMetaDto } from '../local-api/contracts'
import type { PresentationKnowledgeBase } from '../knowledge'
import type { ProjectFile } from '../project-sources/types'
import type { LocalSkipReason } from '../project-sources/localFolderImport'
import { ReleaseLauncher } from './ReleaseLauncher'
import { deriveLauncherState, type ModelChoice } from './launcherState'
import { AnalysisProgress } from './AnalysisProgress'
import { KnowledgeWorkspace } from './KnowledgeWorkspace'
import type { Accent, Appearance } from './ThemeMenu'
import './app.css'
import { ARTIFACT_VALIDATOR_VERSION, PROJECT_LENS_API_VERSION } from '../runtimeVersion'
import { mergeRunEvents } from './runRecovery'
import { resolveCompatibleModel } from './modelResolution'

type Local = { name: string; canonicalPath?: string; files: ProjectFile[]; summary: string; projectType: string; skipped: Record<LocalSkipReason, number>; support: 'supported' | 'too-large' | 'failed'; diagnostics?: string[] }
export function App() {
  const [mode, setMode] = useState<'launcher' | 'analysing' | 'failed' | 'workspace'>('launcher')
  const [codex, setCodex] = useState<CodexStatusDto>(); const [token, setToken] = useState<string>(); const [local, setLocal] = useState<Local>(); const [prepared, setPrepared] = useState(false); const [reading, setReading] = useState(false); const [enrichWithCodex, setEnrichWithCodex] = useState(false)
  const [model, setModel] = useState<ModelChoice>(() => { const saved = localStorage.getItem('project-lens-model'); return saved && saved !== 'automatic' ? saved : undefined })
  const [runId, setRunId] = useState<string>(); const [events, setEvents] = useState<AnalysisEventDto[]>([]); const [status, setStatus] = useState<AnalysisRunStatusDto>(); const [startedAt, setStartedAt] = useState<number>(); const [error, setError] = useState<string>(); const [streamStatus, setStreamStatus] = useState<'connecting' | 'connected' | 'reconnecting'>('connecting'); const [knowledge, setKnowledge] = useState<PresentationKnowledgeBase>(); const [projectNotice, setProjectNotice] = useState<string>(); const [appearance, setAppearance] = useState<Appearance>('dark'); const [accent, setAccent] = useState<Accent>('blue'); const [runtimeCompatible, setRuntimeCompatible] = useState(false); const started = useRef(false); const streamRef = useRef<EventSource | undefined>(undefined); const submitting = useRef(false)
  const api = useCallback((url: string, init: RequestInit = {}) => fetch(url, { ...init, headers: { ...init.headers, ...(token ? { 'x-project-lens-token': token } : {}) } }), [token])
  useEffect(() => { document.documentElement.classList.toggle('dark', appearance === 'dark'); document.documentElement.dataset.accent = accent === 'blue' ? '' : accent }, [appearance, accent])
  const refresh = useCallback(async () => { try { const health = await fetch('/api/runtime/health').then((response) => response.json() as Promise<{ token: string } >); setToken(health.token); const meta = await fetch('/api/meta').then((response) => response.json() as Promise<RuntimeMetaDto>); const compatible = meta.app === 'project-lens' && meta.apiVersion === PROJECT_LENS_API_VERSION && meta.artifactValidatorVersion === ARTIFACT_VALIDATOR_VERSION; setRuntimeCompatible(compatible); if (!compatible) { setCodex({ status: 'unavailable', error: 'Project Lens needs to restart its local service. The browser and local daemon are running different versions.' }); return }; const response = await fetch('/api/codex/status', { headers: { 'x-project-lens-token': health.token } }); setCodex(await response.json() as CodexStatusDto) } catch { setRuntimeCompatible(false); setCodex({ status: 'unavailable', error: 'Project Lens could not reach its local service.' }) } }, [])
  useEffect(() => { if (!started.current) { started.current = true; void refresh() } }, [refresh])
  useEffect(() => { const discovered = codex?.models ?? []; if (codex?.status !== 'ready') return; const resolved = resolveCompatibleModel(discovered, model); if (resolved !== model) { setModel(resolved); if (resolved) localStorage.setItem('project-lens-model', resolved); else localStorage.removeItem('project-lens-model') } }, [codex, model])
  useEffect(() => { if (!import.meta.env.DEV || new URLSearchParams(window.location.search).get('fixture') !== 'deep-guide') return; void import('../fixtures/deepGuideDemoPresentationKnowledge').then(({ deepGuideDemoPresentationKnowledge: demo }) => { setKnowledge(demo); setMode('workspace') }) }, [])
  useEffect(() => { const recovered = new URLSearchParams(window.location.search).get('run'); if (!recovered || !token) return; void api(`/api/runs/${recovered}/recheck`, { method: 'POST' }).then(async (response) => { if (response.ok) { const payload = await response.json() as { report?: PresentationKnowledgeBase }; if (payload.report) { setKnowledge(payload.report); setMode('workspace') } } }) }, [api, token])
  useEffect(() => {
    if (!runId) return
    const controller = new AbortController()
    const poll = async () => {
      try {
        const response = await api(`/api/analysis/${runId}`, { signal: controller.signal }); if (!response.ok) return
        const next = await response.json() as AnalysisRunStatusDto; setStatus(next); setEvents((current) => mergeRunEvents(current, next.events))
        if (next.state === 'failed' || next.state === 'cancelled') { const terminal = next.events.findLast((item) => item.type === 'failed' || item.type === 'cancelled'); setError(terminal?.error ?? (next.state === 'cancelled' ? 'Analysis was cancelled.' : 'Analysis failed before the report was ready.')); setMode('failed'); setRunId(undefined) }
        if (next.state === 'completed' || next.state === 'artifact-ready') { const reportResponse = await api(`/api/analysis/${runId}/report`, { signal: controller.signal }); if (reportResponse.ok) { setKnowledge(await reportResponse.json() as PresentationKnowledgeBase); setMode('workspace'); setRunId(undefined) } }
      } catch { /* SSE remains the primary stream; polling is the recovery path. */ }
    }
    void poll(); const timer = window.setInterval(() => { void poll() }, 3000); return () => { controller.abort(); clearInterval(timer) }
  }, [api, runId])
  const source = local ? { kind: 'local' as const, name: local.name, summary: local.summary, projectType: local.projectType, support: local.support, diagnostics: local.diagnostics } : prepared ? { kind: 'prepared' as const, projectType: 'React/Vite sample' } : undefined
  const rawState = deriveLauncherState(codex, source, model, reading)
  const state = runtimeCompatible ? rawState : { ...rawState, canAnalyse: false, disabledReason: 'Project Lens needs to restart its local service. The browser and local daemon are running different versions.' }
  function usePrepared() { setKnowledge(undefined); setLocal(undefined); setPrepared(true); setError(undefined); setProjectNotice(undefined) }
  function importLocal(name: string, files: ProjectFile[], summary: string, projectType: string, skipped: Record<LocalSkipReason, number>, support: Local['support'], diagnostics?: string[], canonicalPath?: string) { setKnowledge(undefined); setPrepared(false); setLocal({ name, canonicalPath, files, summary, projectType, skipped, support, diagnostics }); setError(undefined); setProjectNotice(undefined) }
  async function importLocalPath(folderPath: string) { const response = await api('/api/source/local-path', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ path: folderPath }) }); const payload = await response.json() as { name?: string; canonicalPath?: string; files?: ProjectFile[]; summary?: string; projectType?: string; skipped?: Record<LocalSkipReason, number>; support?: Local['support']; diagnostics?: string[]; error?: string }; if (!response.ok || !payload.name || !payload.files || !payload.summary || !payload.projectType || !payload.skipped || !payload.support) throw new Error(payload.error ?? 'The folder could not be prepared locally.'); importLocal(payload.name, payload.files, payload.summary, payload.projectType, payload.skipped, payload.support, payload.diagnostics, payload.canonicalPath) }
  async function analyse() { if (!state.canAnalyse || submitting.current) return; submitting.current = true; streamRef.current?.close(); setMode('analysing'); setStartedAt(Date.now()); setEvents([]); setError(undefined); setProjectNotice(undefined); setStreamStatus('connecting'); const body = local ? { name: local.name, projectType: local.projectType, files: local.files, sourcePath: local.canonicalPath, model: model === 'automatic' ? undefined : model } : { model: model === 'automatic' ? undefined : model }; try { const response = await api('/api/runs', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) }); const payload = await response.json() as { runId?: string; error?: string }; if (!response.ok || !payload.runId) { setError(payload.error ?? 'Analysis could not start.'); setMode('failed'); return } setRunId(payload.runId); const stream = new EventSource(`/api/runs/${payload.runId}/events?token=${encodeURIComponent(token ?? '')}`); streamRef.current = stream; stream.onopen = () => setStreamStatus('connected'); stream.onerror = () => { if (!['completed', 'failed', 'cancelled'].includes(status?.state ?? '')) setStreamStatus('reconnecting') }; for (const type of ['queued', 'preparing-evidence', 'run_started', 'thread_started', 'status', 'tool_call', 'tool_result', 'file_write', 'warning', 'artifact_ready', 'completed', 'failed', 'cancelled']) stream.addEventListener(type, (message) => { const event = JSON.parse((message as MessageEvent).data) as AnalysisEventDto; setEvents((current) => event.sequence !== undefined && current.some((item) => item.sequence === event.sequence) ? current : [...current, event]); if (event.type === 'artifact_ready' && event.result) { setKnowledge(event.result); setMode('workspace') } if (event.type === 'completed') { stream.close(); setRunId(undefined) } if (event.type === 'failed' || event.type === 'cancelled') { stream.close(); setError(event.error ?? 'Analysis failed.'); setMode('failed'); setRunId(undefined) } }) } finally { submitting.current = false } }
  if (mode === 'workspace' && knowledge) return <KnowledgeWorkspace knowledge={knowledge} projectNotice={projectNotice} appearance={appearance} accent={accent} onAppearance={setAppearance} onAccent={setAccent} onReturn={() => { setKnowledge(undefined); setProjectNotice(undefined); setMode('launcher') }} onReanalyse={analyse} />
  if (mode === 'analysing' || mode === 'failed') return <AnalysisProgress projectName={local?.name ?? 'Prepared Vite sample'} events={events} startedAt={startedAt} status={status} streamStatus={streamStatus} failed={mode === 'failed' ? error : undefined} onRetry={analyse} onReturn={() => setMode('launcher')} onCancel={() => { if (runId) void api(`/api/runs/${runId}/cancel`, { method: 'POST' }) }} />
  return <ReleaseLauncher state={state} models={codex?.models ?? []} model={model} onModelChange={(value) => { setModel(value); if (value) localStorage.setItem('project-lens-model', value); else localStorage.removeItem('project-lens-model') }} enrichWithCodex={enrichWithCodex} onEnrichWithCodex={setEnrichWithCodex} onUsePrepared={usePrepared} onImportLocal={importLocal} onImportLocalPath={importLocalPath} onSourceReading={setReading} onAnalyse={analyse} />
}
