import { useCallback, useEffect, useRef, useState } from 'react'
import type { AnalysisEventDto, AnalysisRunStatusDto, CodexStatusDto } from '../local-api/contracts'
import type { PresentationKnowledgeBase } from '../knowledge'
import type { ProjectFile } from '../project-sources/types'
import type { LocalSkipReason } from '../project-sources/localFolderImport'
import { ReleaseLauncher } from './ReleaseLauncher'
import { deriveLauncherState, type ModelChoice } from './launcherState'
import { AnalysisProgress } from './AnalysisProgress'
import { KnowledgeWorkspace } from './KnowledgeWorkspace'
import type { Accent, Appearance } from './ThemeMenu'
import './app.css'

type Local = { name: string; files: ProjectFile[]; summary: string; projectType: string; skipped: Record<LocalSkipReason, number>; support: 'supported' | 'too-large' | 'failed'; diagnostics?: string[] }
export function App() {
  const [mode, setMode] = useState<'launcher' | 'analysing' | 'failed' | 'workspace'>('launcher')
  const [codex, setCodex] = useState<CodexStatusDto>(); const [token, setToken] = useState<string>(); const [local, setLocal] = useState<Local>(); const [prepared, setPrepared] = useState(false); const [reading, setReading] = useState(false); const [enrichWithCodex, setEnrichWithCodex] = useState(false)
  const model: ModelChoice = 'automatic'
  const [runId, setRunId] = useState<string>(); const [events, setEvents] = useState<AnalysisEventDto[]>([]); const [status, setStatus] = useState<AnalysisRunStatusDto>(); const [startedAt, setStartedAt] = useState<number>(); const [error, setError] = useState<string>(); const [knowledge, setKnowledge] = useState<PresentationKnowledgeBase>(); const [projectNotice, setProjectNotice] = useState<string>(); const [appearance, setAppearance] = useState<Appearance>('dark'); const [accent, setAccent] = useState<Accent>('blue'); const started = useRef(false)
  const api = useCallback((url: string, init: RequestInit = {}) => fetch(url, { ...init, headers: { ...init.headers, ...(token ? { 'x-project-lens-token': token } : {}) } }), [token])
  useEffect(() => { document.documentElement.classList.toggle('dark', appearance === 'dark'); document.documentElement.dataset.accent = accent === 'blue' ? '' : accent }, [appearance, accent])
  const refresh = useCallback(async () => { try { const health = await fetch('/api/runtime/health').then((response) => response.json() as Promise<{ token: string } >); setToken(health.token); const response = await fetch('/api/codex/status', { headers: { 'x-project-lens-token': health.token } }); setCodex(await response.json() as CodexStatusDto) } catch { setCodex({ status: 'unavailable', error: 'Project Lens could not reach its local service.' }) } }, [])
  useEffect(() => { if (!started.current) { started.current = true; void refresh() } }, [refresh])
  useEffect(() => { if (!runId) return; const controller = new AbortController(); const timer = window.setInterval(() => { void api(`/api/analysis/${runId}`, { signal: controller.signal }).then(async (response) => { if (response.ok) setStatus(await response.json() as AnalysisRunStatusDto) }) }, 3000); return () => { controller.abort(); clearInterval(timer) } }, [api, runId])
  const source = local ? { kind: 'local' as const, name: local.name, summary: local.summary, projectType: local.projectType, support: local.support, diagnostics: local.diagnostics } : prepared ? { kind: 'prepared' as const, projectType: 'React/Vite sample' } : undefined
  const state = deriveLauncherState(codex, source, model, reading)
  function usePrepared() { setKnowledge(undefined); setLocal(undefined); setPrepared(true); setError(undefined); setProjectNotice(undefined) }
  function importLocal(name: string, files: ProjectFile[], summary: string, projectType: string, skipped: Record<LocalSkipReason, number>, support: Local['support'], diagnostics?: string[]) { setKnowledge(undefined); setPrepared(false); setLocal({ name, files, summary, projectType, skipped, support, diagnostics }); setError(undefined); setProjectNotice(undefined) }
  async function importLocalPath(folderPath: string) { const response = await api('/api/source/local-path', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ path: folderPath }) }); const payload = await response.json() as { name?: string; files?: ProjectFile[]; summary?: string; projectType?: string; skipped?: Record<LocalSkipReason, number>; support?: Local['support']; diagnostics?: string[]; error?: string }; if (!response.ok || !payload.name || !payload.files || !payload.summary || !payload.projectType || !payload.skipped || !payload.support) throw new Error(payload.error ?? 'The folder could not be prepared locally.'); importLocal(payload.name, payload.files, payload.summary, payload.projectType, payload.skipped, payload.support, payload.diagnostics) }
  async function analyse() { if (!state.canAnalyse) return; setMode('analysing'); setStartedAt(Date.now()); setEvents([]); setError(undefined); setProjectNotice(undefined); const body = local ? { name: local.name, projectType: local.projectType, files: local.files, enrich: enrichWithCodex, model: model === 'automatic' ? undefined : model } : { enrich: enrichWithCodex, model: model === 'automatic' ? undefined : model }; const response = await api(local ? '/api/analysis/local' : '/api/analysis/sample', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) }); const payload = await response.json() as { runId?: string; error?: string }; if (!response.ok || !payload.runId) { setError(payload.error ?? 'Analysis could not start.'); setMode('failed'); return } setRunId(payload.runId); const stream = new EventSource(`/api/analysis/${payload.runId}/events?token=${encodeURIComponent(token ?? '')}`); for (const type of ['queued', 'preparing-evidence', 'workspace-ready', 'enriching', 'enriched', 'enrichment-unavailable', 'completed', 'failed', 'cancelled']) stream.addEventListener(type, (message) => { const event = JSON.parse((message as MessageEvent).data) as AnalysisEventDto; setEvents((current) => [...current, event]); if ((event.type === 'workspace-ready' || event.type === 'enriched') && event.result) { setKnowledge(event.result); setMode('workspace') } if (event.type === 'enrichment-unavailable') setProjectNotice(event.message); if (event.type === 'completed') { stream.close(); setRunId(undefined) } if (event.type === 'failed' || event.type === 'cancelled') { stream.close(); setError(event.error ?? 'Analysis failed.'); setMode('failed'); setRunId(undefined) } }) }
  if (mode === 'workspace' && knowledge) return <KnowledgeWorkspace knowledge={knowledge} projectNotice={projectNotice} appearance={appearance} accent={accent} onAppearance={setAppearance} onAccent={setAccent} onReturn={() => { setKnowledge(undefined); setProjectNotice(undefined); setMode('launcher') }} onReanalyse={analyse} />
  if (mode === 'analysing' || mode === 'failed') return <AnalysisProgress projectName={local?.name ?? 'Prepared Vite sample'} events={events} startedAt={startedAt} runState={status?.state} lastAnyEventAt={status?.lastAnyEventAt} lastGenuineAgentEventAt={status?.lastGenuineAgentEventAt} failed={mode === 'failed' ? error : undefined} onRetry={analyse} onReturn={() => setMode('launcher')} />
  return <ReleaseLauncher state={state} enrichWithCodex={enrichWithCodex} onEnrichWithCodex={setEnrichWithCodex} onUsePrepared={usePrepared} onImportLocal={importLocal} onImportLocalPath={importLocalPath} onSourceReading={setReading} onAnalyse={analyse} />
}
