import { useRef, useState } from 'react'
import type { ReactNode } from 'react'
import type { PresentationItem, PresentationKnowledgeBase, PresentationProjectPart, PresentationSection } from '../knowledge'
import type { Accent, Appearance } from './ThemeMenu'
import { ThemeMenu } from './ThemeMenu'
import { useControlMotion } from '../motion/useControlMotion'
import { useDisclosureMotion } from '../motion/useDisclosureMotion'
import { useEntranceMotion } from '../motion/useEntranceMotion'
import { useNavigationMotion } from '../motion/useNavigationMotion'
import { usePageTransition } from '../motion/usePageTransition'

type View = 'overview' | 'guide' | 'explore' | 'review'
interface KnowledgeWorkspaceProps { knowledge: PresentationKnowledgeBase; projectNotice?: string; appearance: Appearance; accent: Accent; onAppearance: (value: Appearance) => void; onAccent: (value: Accent) => void; onReturn: () => void; onReanalyse: () => void }

export function KnowledgeWorkspace({ knowledge, projectNotice, appearance, accent, onAppearance, onAccent, onReturn, onReanalyse }: KnowledgeWorkspaceProps) {
  const motionScope = useRef<HTMLElement>(null)
  const navScope = useRef<HTMLElement>(null)
  const contentScope = useRef<HTMLElement>(null)
  const [view, setView] = useState<View>('overview')
  const available = [['overview', 'Overview'], ['guide', 'Guide'], ['explore', 'Explore'], ['review', 'Review']] as const
  useEntranceMotion(motionScope, knowledge.projectName, '.overview > [data-motion-enter]')
  useControlMotion(motionScope)
  useDisclosureMotion(motionScope)
  useNavigationMotion(navScope, view)
  usePageTransition(contentScope, view)
  function openPart(part: PresentationProjectPart) { void part; setView('guide') }
  return <main className="workspace" ref={motionScope}><header className="topbar"><strong className="brand">Project Lens</strong><span className="bar-divider" /><button className="quiet-button" type="button" onClick={onReturn}>Open another project</button><span className="project-title">{knowledge.projectName}</span><span className="source-pill">{knowledge.projectTypeLabel ?? 'Project'}</span><span className="bar-spacer" /><ThemeMenu appearance={appearance} accent={accent} onAppearance={onAppearance} onAccent={onAccent} /><button className="reanalyse-button" type="button" onClick={onReanalyse}>Analyse</button></header><div className="workspace-body"><nav className="sidebar" aria-label="Project sections" ref={navScope}>{available.map(([id, label]) => <button aria-current={view === id ? 'page' : undefined} className={view === id ? 'active' : ''} key={id} type="button" onClick={() => setView(id)}>{label}</button>)}</nav><section className="content" aria-label={`${knowledge.projectName} workspace`} ref={contentScope}>{projectNotice && <p className="project-notice" role="status">{projectNotice}</p>}{view === 'overview' && <Overview knowledge={knowledge} onOpenPart={openPart} />}{view === 'guide' && <Guide knowledge={knowledge} />}{view === 'explore' && <Explore knowledge={knowledge} onOpenPart={openPart} />}{view === 'review' && <Review knowledge={knowledge} />}</section></div></main>
}

function Overview({ knowledge, onOpenPart }: { knowledge: PresentationKnowledgeBase; onOpenPart: (part: PresentationProjectPart) => void }) {
  const overview = knowledge.overview
  return <article className="overview"><p className="eyebrow" data-motion-enter>{knowledge.projectTypeLabel ?? 'Project'}</p><h1 data-motion-enter>{knowledge.projectName}</h1>{knowledge.shortSummary && <p className="lead" data-motion-enter>{knowledge.shortSummary}</p>}{overview?.whatItIs && <Section title="What it is"><p>{overview.whatItIs}</p></Section>}{overview?.whatItDoes?.length ? <ItemSection title="What it does" items={overview.whatItDoes} /> : null}{knowledge.projectParts?.length ? <Section title="Main parts"><div className="project-part-list">{knowledge.projectParts.slice(0, 6).map((part) => <button key={part.id} type="button" onClick={() => onOpenPart(part)}><strong>{part.title}</strong><span>{part.shortExplanation}</span></button>)}</div></Section> : null}{overview?.whereToStart?.length ? <ItemSection title="Where to look first" items={overview.whereToStart} /> : null}{knowledge.technologies?.length ? <Section title="Built with"><div className="topic-list">{knowledge.technologies.map((technology) => <div key={technology.name}><h3>{technology.name}</h3>{technology.explanation && <p>{technology.explanation}</p>}<TechnicalName value={technology.technicalName} /></div>)}</div></Section> : null}{overview?.usefulContext && <p className="subtle" data-motion-enter>{overview.usefulContext}</p>}{knowledge.limitations && <TechnicalDisclosure section={knowledge.limitations} />}</article>
}

function Guide({ knowledge }: { knowledge: PresentationKnowledgeBase }) { const links = [['guide-brief', 'In brief', Boolean(knowledge.shortSummary)], ['guide-parts', 'Main parts', Boolean(knowledge.projectParts?.length)], ['guide-learning', 'Learning order', Boolean(knowledge.learningPath?.length)], ['guide-files', 'Files', Boolean(knowledge.files?.length)], ['guide-technical', 'Technical details', Boolean(knowledge.technicalReference?.length)]] as const; return <article className="guide"><p className="eyebrow">Complete Guide</p><h1>{knowledge.projectName}</h1><nav className="guide-contents" aria-label="Guide contents">{links.filter((link) => link[2]).map(([id, label]) => <a key={id} href={`#${id}`}>{label}</a>)}</nav>{knowledge.shortSummary && <Section id="guide-brief" title="In brief"><p>{knowledge.shortSummary}</p></Section>}{knowledge.projectParts?.length ? <Section id="guide-parts" title="Main parts"><div className="topic-list">{knowledge.projectParts.map((part) => <div key={part.id}><h3>{part.title}</h3><p>{part.shortExplanation}</p><TechnicalName value={part.technicalName} /></div>)}</div></Section> : null}{knowledge.learningPath?.length ? <Section id="guide-learning" title="A good learning order"><ItemSection title="" items={knowledge.learningPath} ordered /></Section> : null}{knowledge.files?.length ? <Section id="guide-files" title="Files"><FileList files={knowledge.files} /></Section> : null}{knowledge.technicalReference?.length ? <Section id="guide-technical" title="Technical details"><TechnicalDetails sections={knowledge.technicalReference} /></Section> : null}</article> }


function Review({ knowledge }: { knowledge: PresentationKnowledgeBase }) { const items = knowledge.projectParts?.flatMap((part) => part.reviewBeforeCopying?.map((item) => ({ ...item, part: part.title })) ?? []) ?? []; return <article><p className="eyebrow">Review</p><h1>Choices worth checking</h1><p className="lead">These notes are evidence-backed prompts for your own judgement, not automatic warnings.</p>{items.length ? items.map((item) => <div className="decision" key={`${item.part}-${item.id}`}><strong>{item.title}</strong><p>{item.explanation}</p><span className="review">{item.part}</span><Evidence references={item.relatedEvidence} /></div>) : <p className="subtle">No review notes were recorded for this project.</p>}{knowledge.limitations && <TechnicalDisclosure section={knowledge.limitations} />}</article> }

function Explore({ knowledge, onOpenPart }: { knowledge: PresentationKnowledgeBase; onOpenPart: (part: PresentationProjectPart) => void }) { const [query, setQuery] = useState(''); const term = query.trim().toLowerCase(); const parts = knowledge.projectParts ?? []; const results = parts.flatMap((part) => { const values = [part.title, part.shortExplanation, part.technicalName, ...(part.relatedFiles ?? []), ...(part.items?.flatMap((item) => [item.title, item.technicalName, item.explanation] ) ?? [])].filter(Boolean).join(' ').toLowerCase(); return !term || values.includes(term) ? [{ type: 'Guide', title: part.title, explanation: part.shortExplanation ?? 'Project area', path: part.relatedFiles?.[0], part }] : [] }); const files = (knowledge.files ?? []).filter((file) => !term || `${file.path} ${file.title ?? ''} ${file.explanation ?? ''}`.toLowerCase().includes(term)); return <article><p className="eyebrow">Explore</p><h1>Search this project</h1><label className="explore-search">Search project knowledge<input type="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search parts, concepts, files…" /></label>{!term && <p className="subtle">Search the reviewed explanation already in this workspace. No new analysis runs.</p>}<div className="search-results"><h2>Project parts</h2>{results.length ? results.map((result) => <button type="button" key={result.part.id} onClick={() => onOpenPart(result.part)}><strong>{result.title}</strong><span>{result.explanation}</span>{result.path && <code>{result.path}</code>}</button>) : <p className="subtle">No matching project parts.</p>}<h2>Files</h2>{files.length ? files.slice(0, 20).map((file) => <div className="file-row" key={file.path}><code>{file.path}</code><span>{file.explanation ?? 'File reference'}</span></div>) : <p className="subtle">No matching files.</p>}</div></article> }

function ItemSection({ title, items, ordered = false }: { title: string; items: PresentationItem[]; ordered?: boolean }) { const content = items.map((item) => <div key={item.id}><h3>{item.title}</h3>{item.explanation && <p>{item.explanation}</p>}{item.whyItMatters && <p className="subtle">Why it matters: {item.whyItMatters}</p>}<TechnicalName value={item.technicalName} /><Evidence references={item.relatedEvidence} /></div>); return <Section title={title}>{ordered ? <ol className="learning-list">{items.map((item) => <li key={item.id}><strong>{item.title}</strong>{item.explanation && <span>{item.explanation}</span>}</li>)}</ol> : <div className="topic-list">{content}</div>}</Section> }
function FileList({ files }: { files: NonNullable<PresentationKnowledgeBase['files']> }) { return <div className="file-list">{files.map((file) => <div className="file-row" key={file.path}><code title={file.path}>{file.path}</code><span>{file.explanation ?? 'The file was found, but its exact role could not be confirmed.'}</span>{file.analysisStatus && file.analysisStatus !== 'analysed' && <em>{file.analysisStatus === 'uncertain' ? 'Role uncertain' : 'Partially inspected'}</em>}<TechnicalName value={file.technicalName} /></div>)}</div> }
function FilePaths({ paths }: { paths: string[] }) { return <div className="file-list">{paths.map((path) => <div className="file-row" key={path}><code>{path}</code></div>)}</div> }
function TechnicalName({ value }: { value?: string }) { return value ? <p className="subtle">Technical name: {value}</p> : null }
function Evidence({ references }: { references?: { path: string; fact?: string }[] }) { return references?.length ? <details className="disclosure"><summary>View technical evidence</summary><ul>{references.map((reference) => <li key={`${reference.path}-${reference.fact ?? ''}`}><code>{reference.path}</code>{reference.fact ? ` — ${reference.fact}` : ''}</li>)}</ul></details> : null }
function TechnicalDisclosure({ section }: { section: PresentationSection }) { return section.items?.length || section.evidenceReferences?.length || section.relatedFiles?.length || section.importRelationships?.length || section.codeExamples?.length ? <details className="disclosure"><summary>{section.id === 'analysis-notes' ? 'View analysis notes' : 'View technical details'}</summary>{section.shortExplanation && <p>{section.shortExplanation}</p>}{section.items?.length ? <div className="topic-list">{section.items.map((item) => <div key={item.id}><h3>{item.technicalName ?? item.title}</h3>{item.explanation && <p>{item.explanation}</p>}<Evidence references={item.relatedEvidence} /></div>)}</div> : null}{section.relatedFiles?.length ? <FilePaths paths={section.relatedFiles} /> : null}{section.importRelationships?.length ? <details className="disclosure"><summary>View import relationships</summary><ul>{section.importRelationships.map((relationship) => <li key={relationship}>{relationship}</li>)}</ul></details> : null}{section.codeExamples?.length ? <details className="disclosure"><summary>View code excerpt</summary>{section.codeExamples.map((example) => <pre key={example.label}><code>{example.code}</code></pre>)}</details> : null}<Evidence references={section.evidenceReferences} /></details> : null }
function TechnicalDetails({ sections }: { sections: PresentationSection[] }) { return <Section title="Technical details">{sections.map((section) => <TechnicalDisclosure key={section.id} section={section} />)}</Section> }
function Section({ title, children, id }: { title: string; children: ReactNode; id?: string }) { return <section className="content-section" id={id} data-motion-enter>{title && <h2>{title}</h2>}{children}</section> }
