import { useRef, useState } from 'react'
import type { ReactNode } from 'react'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import rehypeSanitize from 'rehype-sanitize'
import type { PresentationItem, PresentationKnowledgeBase, PresentationProjectPart, PresentationSection } from '../knowledge'
import { parseSemanticReportV2 } from '../knowledge/reportV2'
import type { Accent, Appearance } from './ThemeMenu'
import { ThemeMenu } from './ThemeMenu'
import { useControlMotion } from '../motion/useControlMotion'
import { useDisclosureMotion } from '../motion/useDisclosureMotion'
import { useEntranceMotion } from '../motion/useEntranceMotion'
import { useNavigationMotion } from '../motion/useNavigationMotion'
import { usePageTransition } from '../motion/usePageTransition'

type View = 'overview' | 'guide' | 'explore' | 'review'
interface KnowledgeWorkspaceProps { knowledge: PresentationKnowledgeBase; projectNotice?: string; appearance: Appearance; accent: Accent; onAppearance: (value: Appearance) => void; onAccent: (value: Accent) => void; onReturn: () => void; onReanalyse: () => void }

export function KnowledgeWorkspace({ knowledge, projectNotice, appearance, accent, onAppearance, onAccent, onReturn, onReanalyse }: KnowledgeWorkspaceProps) {
  const motionScope = useRef<HTMLElement>(null)
  const navScope = useRef<HTMLElement>(null)
  const contentScope = useRef<HTMLElement>(null)
  const [view, setView] = useState<View>('overview')
  const available = [['overview', 'Overview'], ['guide', 'Complete Guide'], ['explore', 'Files and evidence'], ['review', 'Unknowns']] as const
  useEntranceMotion(motionScope, knowledge.projectName, '.overview > [data-motion-enter]')
  useControlMotion(motionScope)
  useDisclosureMotion(motionScope)
  useNavigationMotion(navScope, view)
  usePageTransition(contentScope, view)
  function openPart(part: PresentationProjectPart) { void part; setView('guide') }
  return <main className="workspace" ref={motionScope}><header className="topbar"><strong className="brand">Project Lens</strong><span className="bar-divider" /><button className="quiet-button" type="button" onClick={onReturn}>Open another project</button><span className="project-title">{knowledge.projectName}</span><span className="source-pill">{knowledge.projectTypeLabel ?? 'Project'}</span><span className="bar-spacer" /><ThemeMenu appearance={appearance} accent={accent} onAppearance={onAppearance} onAccent={onAccent} /><button className="reanalyse-button" type="button" onClick={onReanalyse}>Analyse</button></header><div className="workspace-body"><nav className="sidebar" aria-label="Project sections" ref={navScope}>{available.map(([id, label]) => <button aria-current={view === id ? 'page' : undefined} className={view === id ? 'active' : ''} key={id} type="button" onClick={() => setView(id)}>{label}</button>)}</nav><section className="content" aria-label={`${knowledge.projectName} workspace`} ref={contentScope}>{projectNotice && <p className="project-notice" role="status">{projectNotice}</p>}{view === 'overview' && <Overview knowledge={knowledge} onOpenPart={openPart} />}{view === 'guide' && <Guide knowledge={knowledge} />}{view === 'explore' && <Explore knowledge={knowledge} onOpenPart={openPart} />}{view === 'review' && <Review knowledge={knowledge} />}</section></div></main>
}

function Overview({ knowledge, onOpenPart }: { knowledge: PresentationKnowledgeBase; onOpenPart: (part: PresentationProjectPart) => void }) {
  const overview = knowledge.overview
  const report = knowledge.overviewMarkdown ? parseSemanticReportV2(knowledge.overviewMarkdown, 'overview') : null
  if (report) return <SemanticOverview report={report} knowledge={knowledge} />
  const section = (id: string) => knowledge.sections?.find((item) => item.id === id)
  return <article className="overview"><p className="eyebrow" data-motion-enter>{knowledge.projectTypeLabel ?? 'Project'}</p><h1 data-motion-enter>{knowledge.projectName}</h1>{knowledge.overviewMarkdown ? <ArtifactMarkdown text={knowledge.overviewMarkdown} knowledge={knowledge} /> : <>{knowledge.shortSummary && <p className="lead" data-motion-enter>{knowledge.shortSummary}</p>}{overview?.whatItIs && <Section title="What this project does"><p>{overview.whatItIs}</p></Section>}</>}{section('concepts')?.items && <ItemSection title="Concepts to know" items={section('concepts')!.items!} />}{section('how-it-works')?.items && <ItemSection title="How the project works" items={section('how-it-works')!.items!} ordered />}{section('start-here')?.items && <ItemSection title="Start here" items={section('start-here')!.items!} ordered />}{knowledge.projectParts?.length ? <Section title="Main project areas"><div className="project-part-list">{knowledge.projectParts.slice(0, 6).map((part) => <button key={part.id} type="button" onClick={() => onOpenPart(part)}><strong>{part.title}</strong><span>{part.shortExplanation}</span></button>)}</div></Section> : null}{section('commands')?.items && <ItemSection title="Commands at a glance" items={section('commands')!.items!} />}{overview?.whereToStart?.length ? <ItemSection title="Where to look first" items={overview.whereToStart} /> : null}{knowledge.technologies?.length ? <Section title="Built with"><div className="topic-list">{knowledge.technologies.map((technology) => <div key={technology.name}><h3>{technology.name}</h3>{technology.explanation && <p>{technology.explanation}</p>}<TechnicalName value={technology.technicalName} /></div>)}</div></Section> : null}<ProjectMap knowledge={knowledge} />{overview?.usefulContext && <p className="subtle" data-motion-enter>{overview.usefulContext}</p>}{knowledge.limitations && <TechnicalDisclosure section={knowledge.limitations} />}</article>
}

function Guide({ knowledge }: { knowledge: PresentationKnowledgeBase }) { const report = knowledge.completeGuideMarkdown ? parseSemanticReportV2(knowledge.completeGuideMarkdown, 'complete-guide') : null; if (report) return <SemanticGuide report={report} knowledge={knowledge} />; if (knowledge.completeGuideMarkdown) return <article className="guide"><p className="eyebrow">Complete Guide</p><h1>{knowledge.projectName}</h1><ArtifactMarkdown text={knowledge.completeGuideMarkdown} knowledge={knowledge} /></article>; const links = [['guide-brief', 'In brief', Boolean(knowledge.shortSummary)], ...((knowledge.sections ?? []).map((section) => [section.id, section.title, true] as const)), ['guide-parts', 'Main parts', Boolean(knowledge.projectParts?.length)], ['guide-learning', 'Learning order', Boolean(knowledge.learningPath?.length)], ['guide-files', 'Files', Boolean(knowledge.files?.length)], ['guide-technical', 'Technical details', Boolean(knowledge.technicalReference?.length)]] as const; return <article className="guide"><p className="eyebrow">Complete Guide</p><h1>{knowledge.projectName}</h1><nav className="guide-contents" aria-label="Guide contents">{links.filter((link) => link[2]).map(([id, label]) => <a key={id} href={`#${id}`}>{label}</a>)}</nav>{knowledge.shortSummary && <Section id="guide-brief" title="In brief"><p>{knowledge.shortSummary}</p></Section>}{knowledge.sections?.map((section) => <Section key={section.id} id={section.id} title={section.title}>{section.items?.length ? <ItemSection title="" items={section.items} /> : <p>{section.shortExplanation}</p>}</Section>)}{knowledge.projectParts?.length ? <Section id="guide-parts" title="Main parts"><div className="topic-list">{knowledge.projectParts.map((part) => <div key={part.id}><h3>{part.title}</h3><p>{part.shortExplanation}</p><TechnicalName value={part.technicalName} /></div>)}</div></Section> : null}{knowledge.learningPath?.length ? <Section id="guide-learning" title="Suggested learning order"><ItemSection title="" items={knowledge.learningPath} ordered /></Section> : null}{knowledge.files?.length ? <Section id="guide-files" title="Important files"><FileList files={knowledge.files} /></Section> : null}{knowledge.technicalReference?.length ? <Section id="guide-technical" title="How the parts connect"><TechnicalDetails sections={knowledge.technicalReference} /></Section> : null}</article> }

function SemanticOverview({ report, knowledge }: { report: NonNullable<ReturnType<typeof parseSemanticReportV2>>; knowledge: PresentationKnowledgeBase }) { const section = (id: string) => report.sections.find((item) => item.id === id); const glance = section('at-a-glance'); const flow = section('how-it-works'); const start = section('start-here'); return <article className="overview report-v2"><p className="eyebrow">Project overview</p><h1>{report.title}</h1><p className="lead">{report.introduction}</p>{start && <section className="report-start"><h2>Start here</h2><p>Use this reading path to build the project’s mental model before following technical details.</p><div className="report-reading"><ArtifactMarkdown text={start.markdown} knowledge={knowledge} /></div></section>}{glance && <section className="report-glance"><h2>At a glance</h2><ArtifactMarkdown text={glance.markdown} knowledge={knowledge} /></section>}{section('what-it-does') && <Section title="How to think about this project"><ArtifactMarkdown text={section('what-it-does')!.markdown} knowledge={knowledge} /></Section>}{flow && <Section title="How the project works"><div className="report-flow"><ArtifactMarkdown text={flow.markdown} knowledge={knowledge} /></div></Section>}{section('project-areas') && <Section title="Project areas"><ArtifactMarkdown text={section('project-areas')!.markdown} knowledge={knowledge} /></Section>}{section('run-or-use-it') && <Section title="Running the project"><ArtifactMarkdown text={section('run-or-use-it')!.markdown} knowledge={knowledge} /></Section>}<EvidenceDisclosure knowledge={knowledge} />{section('known-gaps') && <aside className="report-gaps"><h2>What is still unclear</h2><ArtifactMarkdown text={section('known-gaps')!.markdown} knowledge={knowledge} /></aside>}<AnalysisCoverage knowledge={knowledge} /></article> }
function SemanticGuide({ report, knowledge }: { report: NonNullable<ReturnType<typeof parseSemanticReportV2>>; knowledge: PresentationKnowledgeBase }) { return <article className="guide report-v2"><p className="eyebrow">Complete Guide</p><h1>{report.title}</h1><p className="lead">{report.introduction}</p><nav className="guide-contents report-contents" aria-label="Guide contents">{report.sections.map((section) => <a key={section.id} href={`#report-${section.id}`}>{section.title}</a>)}</nav>{report.sections.map((section) => <Section key={section.id} id={`report-${section.id}`} title={section.title}><ArtifactMarkdown text={section.markdown} knowledge={knowledge} /></Section>)}<ProjectMap knowledge={knowledge} /><AnalysisCoverage knowledge={knowledge} /></article> }
function AnalysisCoverage({ knowledge }: { knowledge: PresentationKnowledgeBase }) { return <details className="disclosure report-coverage"><summary>Analysis coverage</summary><p>{knowledge.files?.length ?? 0} verified project files are available in this report.</p>{knowledge.limitations?.shortExplanation && <p>{knowledge.limitations.shortExplanation}</p>}</details> }
function EvidenceDisclosure({ knowledge }: { knowledge: PresentationKnowledgeBase }) { const files = knowledge.files?.slice(0, 8) ?? []; if (!files.length) return null; return <details className="disclosure report-evidence"><summary>View evidence</summary><p>These verified project files support the report. Open a path to find it in the file list.</p><ul>{files.map((file) => <li key={file.path}><a href={`#project-file-${encodeURIComponent(file.path)}`}><code>{file.path}</code></a>{file.explanation ? ` — ${file.explanation}` : ''}</li>)}</ul></details> }

function ArtifactMarkdown({ text, knowledge }: { text: string; knowledge: PresentationKnowledgeBase }) {
  const known = new Set([...(knowledge.files?.map((file) => file.path) ?? []), ...(knowledge.projectParts?.flatMap((part) => part.relatedFiles ?? []) ?? [])])
  const sourcePath = (href: string) => href.replaceAll('\\', '/').replace(/^\.\.\/source\//i, '').replace(/^\.\//, '').replace(/^source\//i, '')
  return <div className="artifact-markdown"><ReactMarkdown remarkPlugins={[remarkGfm]} rehypePlugins={[rehypeSanitize]} components={{ a: ({ href = '', children }) => {
    if (/^https?:\/\//i.test(href)) return <a href={href} rel="noopener noreferrer" target="_blank">{children}</a>
    const file = sourcePath(href)
    if (known.has(file)) return <a href={`#project-file-${encodeURIComponent(file)}`} data-verified-source={file}>{file}</a>
    return <code title="Runtime-generated or unverified path">{children}</code>
  }, code: ({ children, ...props }) => <code {...props}>{typeof children === 'string' ? sourcePath(children) : children}</code> }}>{text}</ReactMarkdown></div>
}


function Review({ knowledge }: { knowledge: PresentationKnowledgeBase }) { const items = knowledge.projectParts?.flatMap((part) => part.reviewBeforeCopying?.map((item) => ({ ...item, part: part.title })) ?? []) ?? []; return <article><p className="eyebrow">Review</p><h1>Choices worth checking</h1><p className="lead">These notes are evidence-backed prompts for your own judgement, not automatic warnings.</p>{items.length ? items.map((item) => <div className="decision" key={`${item.part}-${item.id}`}><strong>{item.title}</strong><p>{item.explanation}</p><span className="review">{item.part}</span><Evidence references={item.relatedEvidence} /></div>) : <p className="subtle">No review notes were recorded for this project.</p>}{knowledge.limitations && <TechnicalDisclosure section={knowledge.limitations} />}</article> }

function Explore({ knowledge, onOpenPart }: { knowledge: PresentationKnowledgeBase; onOpenPart: (part: PresentationProjectPart) => void }) { const [query, setQuery] = useState(''); const term = query.trim().toLowerCase(); const parts = knowledge.projectParts ?? []; const results = parts.flatMap((part) => { const values = [part.title, part.shortExplanation, part.technicalName, ...(part.relatedFiles ?? []), ...(part.items?.flatMap((item) => [item.title, item.technicalName, item.explanation] ) ?? [])].filter(Boolean).join(' ').toLowerCase(); return !term || values.includes(term) ? [{ type: 'Guide', title: part.title, explanation: part.shortExplanation ?? 'Project area', path: part.relatedFiles?.[0], part }] : [] }); const files = (knowledge.files ?? []).filter((file) => !term || `${file.path} ${file.title ?? ''} ${file.explanation ?? ''}`.toLowerCase().includes(term)); return <article><p className="eyebrow">Explore</p><h1>Search this project</h1><label className="explore-search">Search project knowledge<input type="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search parts, concepts, files…" /></label>{!term && <p className="subtle">Search the reviewed explanation already in this workspace. No new analysis runs.</p>}<div className="search-results"><h2>Project parts</h2>{results.length ? results.map((result) => <button type="button" key={result.part.id} onClick={() => onOpenPart(result.part)}><strong>{result.title}</strong><span>{result.explanation}</span>{result.path && <code>{result.path}</code>}</button>) : <p className="subtle">No matching project parts.</p>}<h2>Files</h2>{files.length ? files.slice(0, 20).map((file) => <div className="file-row" key={file.path}><code>{file.path}</code><span>{file.explanation ?? 'File reference'}</span></div>) : <p className="subtle">No matching files.</p>}</div><ProjectMap knowledge={knowledge} /></article> }

type MapMode = 'responsibilities' | 'repository' | 'connections' | 'symbols'

function ProjectMap({ knowledge }: { knowledge: PresentationKnowledgeBase }) {
  const [mode, setMode] = useState<MapMode>('responsibilities')
  const [selectedPath, setSelectedPath] = useState<string | undefined>()
  const files = knowledge.files ?? []
  const paths = new Set(files.map((file) => file.path))
  const edges = (knowledge.relationships ?? []).filter((edge) => paths.has(edge.fromPath) && paths.has(edge.toPath)).slice(0, 60)
  const selected = files.find((file) => file.path === selectedPath) ?? files[0]
  const related = selected ? edges.filter((edge) => edge.fromPath === selected.path || edge.toPath === selected.path) : []
  const symbols = selected ? (knowledge.symbols ?? []).filter((symbol) => symbol.path === selected.path) : []
  const modes: [MapMode, string][] = [['responsibilities', 'Responsibility tree'], ['repository', 'Repository tree'], ['connections', 'File connections'], ['symbols', 'Important symbols']]
  if (!files.length && !knowledge.projectParts?.length) return null
  const commands = knowledge.sections?.find((section) => section.id === 'commands')?.items ?? []
  const concepts = knowledge.sections?.find((section) => section.id === 'concepts')?.items ?? []
  return <Section id="project-map" title="Evidence-backed project map"><p className="subtle">This map only shows selected readable files and confirmed static imports. It does not claim to be a call graph.</p><div className="part-tabs" role="tablist" aria-label="Project map views">{modes.map(([id, label]) => <button aria-selected={mode === id} className={mode === id ? 'active' : ''} key={id} role="tab" type="button" onClick={() => setMode(id)}>{label}</button>)}</div>{mode === 'responsibilities' && <ResponsibilityTree knowledge={knowledge} onSelect={setSelectedPath} />}{mode === 'repository' && <RepositoryTree files={files} onSelect={setSelectedPath} />}{mode === 'connections' && <ConnectionMap edges={edges} files={files} onSelect={setSelectedPath} />}{mode === 'symbols' && <SymbolList symbols={knowledge.symbols ?? []} onSelect={setSelectedPath} />}{selected && <aside className="map-detail" aria-live="polite"><p className="eyebrow">Selected file</p><h3><code>{selected.path}</code></h3><p>{selected.explanation ?? 'This file was selected from the readable project evidence.'}</p>{related.length ? <><h4>Confirmed file communication</h4><ul>{related.map((edge) => <li key={`${edge.fromPath}-${edge.toPath}`}>{edge.fromPath === selected.path ? <><code>{edge.fromPath}</code> imports <code>{edge.toPath}</code></> : <><code>{edge.fromPath}</code> imports this file</>}</li>)}</ul></> : <p className="subtle">No resolved import relationship connects this selected file to another selected file.</p>}{symbols.length ? <><h4>Declarations found here</h4><ul>{symbols.map((symbol) => <li key={`${symbol.path}-${symbol.line}-${symbol.name}`}><code>{symbol.signature}</code> <span className="subtle">{symbol.kind}, line {symbol.line}</span></li>)}</ul></> : null}<Evidence references={[{ path: selected.path, fact: 'Readable project file inspected by deterministic analysis.' }]} /></aside>}{edges.length ? <details className="disclosure"><summary>Trace a verified file flow</summary><ol>{edges.slice(0, 4).map((edge) => <li key={`${edge.fromPath}-${edge.toPath}`}>The module <code>{edge.fromPath}</code> makes exports from <code>{edge.toPath}</code> available through a confirmed static import.</li>)}</ol></details> : null}{commands.length ? <details className="disclosure"><summary>Explain verified commands</summary><ul>{commands.map((command) => <li key={command.id}><code>{command.title}</code>{command.explanation ? ` — ${command.explanation}` : ''}</li>)}</ul></details> : null}{concepts.length ? <details className="disclosure"><summary>Project glossary</summary><dl>{concepts.map((concept) => <div key={concept.id}><dt>{concept.technicalName ?? concept.title}</dt><dd>{concept.explanation}</dd></div>)}</dl></details> : null}</Section>
}

function ResponsibilityTree({ knowledge, onSelect }: { knowledge: PresentationKnowledgeBase; onSelect: (path: string) => void }) { const parts = knowledge.projectParts ?? []; return parts.length ? <ul className="project-tree">{parts.map((part) => <li key={part.id}><strong>{part.title}</strong><span>{part.shortExplanation}</span><ul>{(part.relatedFiles ?? []).map((path) => <li key={path}><button type="button" onClick={() => onSelect(path)}><code>{path}</code></button></li>)}</ul></li>)}</ul> : <p className="subtle">No responsibility groups were supported by the current evidence.</p> }
function RepositoryTree({ files, onSelect }: { files: NonNullable<PresentationKnowledgeBase['files']>; onSelect: (path: string) => void }) { return <ul className="project-tree">{files.map((file) => <li key={file.path}><button type="button" onClick={() => onSelect(file.path)}><code>{file.path}</code></button></li>)}</ul> }
function ConnectionMap({ edges, files, onSelect }: { edges: NonNullable<PresentationKnowledgeBase['relationships']>; files: NonNullable<PresentationKnowledgeBase['files']>; onSelect: (path: string) => void }) { return edges.length ? <ul className="connection-list">{edges.map((edge) => <li key={`${edge.fromPath}-${edge.toPath}`}><button type="button" onClick={() => onSelect(edge.fromPath)}><code>{edge.fromPath}</code></button><span aria-hidden="true"> → imports → </span><button type="button" onClick={() => onSelect(edge.toPath)}><code>{edge.toPath}</code></button><em>Verified</em></li>)}</ul> : <p className="subtle">No resolved imports connect the selected evidence files. {files.length ? 'Choose a file to inspect its role instead.' : ''}</p> }
function SymbolList({ symbols, onSelect }: { symbols: NonNullable<PresentationKnowledgeBase['symbols']>; onSelect: (path: string) => void }) { return symbols.length ? <ul className="symbol-list">{symbols.map((symbol) => <li key={`${symbol.path}-${symbol.line}-${symbol.name}`}><button type="button" onClick={() => onSelect(symbol.path)}><strong>{symbol.name}</strong><code>{symbol.signature}</code><span>{symbol.kind} · <code>{symbol.path}:{symbol.line}</code></span></button></li>)}</ul> : <p className="subtle">No supported top-level declarations were found in the selected evidence files.</p> }

function ItemSection({ title, items, ordered = false }: { title: string; items: PresentationItem[]; ordered?: boolean }) { const content = items.map((item) => <div key={item.id}><h3>{item.title}</h3>{item.explanation && <p>{item.explanation}</p>}{item.whyItMatters && <p className="subtle">Why it matters: {item.whyItMatters}</p>}<TechnicalName value={item.technicalName} /><Evidence references={item.relatedEvidence} /></div>); return <Section title={title}>{ordered ? <ol className="learning-list">{items.map((item) => <li key={item.id}><strong>{item.title}</strong>{item.explanation && <span>{item.explanation}</span>}</li>)}</ol> : <div className="topic-list">{content}</div>}</Section> }
function FileList({ files }: { files: NonNullable<PresentationKnowledgeBase['files']> }) { return <div className="file-list">{files.map((file) => <div className="file-row" id={`project-file-${encodeURIComponent(file.path)}`} key={file.path}><code title={file.path}>{file.path}</code><span>{file.explanation ?? 'The file was found, but its exact role could not be confirmed.'}</span>{file.analysisStatus && file.analysisStatus !== 'analysed' && <em>{file.analysisStatus === 'uncertain' ? 'Role uncertain' : 'Partially inspected'}</em>}<TechnicalName value={file.technicalName} /></div>)}</div> }
function FilePaths({ paths }: { paths: string[] }) { return <div className="file-list">{paths.map((path) => <div className="file-row" key={path}><code>{path}</code></div>)}</div> }
function TechnicalName({ value }: { value?: string }) { return value ? <p className="subtle">Technical name: {value}</p> : null }
function Evidence({ references }: { references?: { path: string; fact?: string }[] }) { return references?.length ? <details className="disclosure"><summary>View technical evidence</summary><ul>{references.map((reference) => <li key={`${reference.path}-${reference.fact ?? ''}`}><code>{reference.path}</code>{reference.fact ? ` — ${reference.fact}` : ''}</li>)}</ul></details> : null }
function TechnicalDisclosure({ section }: { section: PresentationSection }) { return section.items?.length || section.evidenceReferences?.length || section.relatedFiles?.length || section.importRelationships?.length || section.codeExamples?.length ? <details className="disclosure"><summary>{section.id === 'analysis-notes' ? 'View analysis notes' : 'View technical details'}</summary>{section.shortExplanation && <p>{section.shortExplanation}</p>}{section.items?.length ? <div className="topic-list">{section.items.map((item) => <div key={item.id}><h3>{item.technicalName ?? item.title}</h3>{item.explanation && <p>{item.explanation}</p>}<Evidence references={item.relatedEvidence} /></div>)}</div> : null}{section.relatedFiles?.length ? <FilePaths paths={section.relatedFiles} /> : null}{section.importRelationships?.length ? <details className="disclosure"><summary>View import relationships</summary><ul>{section.importRelationships.map((relationship) => <li key={relationship}>{relationship}</li>)}</ul></details> : null}{section.codeExamples?.length ? <details className="disclosure"><summary>View code excerpt</summary>{section.codeExamples.map((example) => <pre key={example.label}><code>{example.code}</code></pre>)}</details> : null}<Evidence references={section.evidenceReferences} /></details> : null }
function TechnicalDetails({ sections }: { sections: PresentationSection[] }) { return <Section title="Technical details">{sections.map((section) => <TechnicalDisclosure key={section.id} section={section} />)}</Section> }
function Section({ title, children, id }: { title: string; children: ReactNode; id?: string }) { return <section className="content-section" id={id} data-motion-enter>{title && <h2>{title}</h2>}{children}</section> }
