import { useRef, useState } from 'react'
import type { ReactNode } from 'react'
import type { PresentationItem, PresentationKnowledgeBase, PresentationProjectPart, PresentationSection } from '../knowledge'
import type { Accent, Appearance } from './ThemeMenu'
import { ThemeMenu } from './ThemeMenu'
import { useControlMotion } from '../motion/useControlMotion'
import { useDisclosureMotion } from '../motion/useDisclosureMotion'
import { useEntranceMotion } from '../motion/useEntranceMotion'
import { useNavigationMotion } from '../motion/useNavigationMotion'
import { usePageTransition } from '../motion/usePageTransition'

type View = 'overview' | 'guide' | 'parts' | 'technologies' | 'files' | 'decisions'
interface KnowledgeWorkspaceProps { knowledge: PresentationKnowledgeBase; appearance: Appearance; accent: Accent; onAppearance: (value: Appearance) => void; onAccent: (value: Accent) => void; onReturn: () => void; onReanalyse: () => void }

export function KnowledgeWorkspace({ knowledge, appearance, accent, onAppearance, onAccent, onReturn, onReanalyse }: KnowledgeWorkspaceProps) {
  const motionScope = useRef<HTMLElement>(null)
  const navScope = useRef<HTMLElement>(null)
  const contentScope = useRef<HTMLElement>(null)
  const [view, setView] = useState<View>('overview')
  const [partId, setPartId] = useState(knowledge.projectParts?.[0]?.id)
  const selectedPart = knowledge.projectParts?.find((part) => part.id === partId)
  const available = [['overview', 'Overview', true], ['guide', 'Complete Guide', true], ['parts', 'Project parts', Boolean(knowledge.projectParts?.length)], ['technologies', 'Technologies', Boolean(knowledge.technologies?.length)], ['files', 'Files', Boolean(knowledge.files?.length)], ['decisions', 'Review before copying', Boolean(knowledge.projectParts?.some((part) => part.reviewBeforeCopying?.length))]] as const
  useEntranceMotion(motionScope, knowledge.projectName, '.overview > [data-motion-enter]')
  useControlMotion(motionScope)
  useDisclosureMotion(motionScope)
  useNavigationMotion(navScope, view)
  usePageTransition(contentScope, view === 'parts' ? `${view}-${partId}` : view)
  function openPart(part: PresentationProjectPart) { setPartId(part.id); setView('parts') }
  return <main className="workspace" ref={motionScope}><header className="topbar"><strong className="brand">Project Lens</strong><span className="bar-divider" /><button className="quiet-button" type="button" onClick={onReturn}>Open another project</button><span className="project-title">{knowledge.projectName}</span><span className="source-pill">{knowledge.projectTypeLabel ?? 'Project'}</span><span className="bar-spacer" /><ThemeMenu appearance={appearance} accent={accent} onAppearance={onAppearance} onAccent={onAccent} /><button className="reanalyse-button" type="button" onClick={onReanalyse}>Analyse</button></header><div className="workspace-body"><nav className="sidebar" aria-label="Project sections" ref={navScope}>{available.filter((item) => item[2]).map(([id, label]) => <button aria-current={view === id ? 'page' : undefined} className={view === id ? 'active' : ''} key={id} type="button" onClick={() => setView(id)}>{label}</button>)}</nav><section className="content" aria-label={`${knowledge.projectName} workspace`} ref={contentScope}>{view === 'overview' && <Overview knowledge={knowledge} onOpenPart={openPart} />}{view === 'guide' && <Guide knowledge={knowledge} />}{view === 'parts' && <Parts knowledge={knowledge} selected={selectedPart} onSelect={openPart} />}{view === 'technologies' && <Technologies knowledge={knowledge} />}{view === 'files' && <Files knowledge={knowledge} />}{view === 'decisions' && <Decisions knowledge={knowledge} />}</section></div></main>
}

function Overview({ knowledge, onOpenPart }: { knowledge: PresentationKnowledgeBase; onOpenPart: (part: PresentationProjectPart) => void }) {
  const overview = knowledge.overview
  return <article className="overview"><p className="eyebrow" data-motion-enter>{knowledge.projectTypeLabel ?? 'Project'}</p><h1 data-motion-enter>{knowledge.projectName}</h1>{knowledge.shortSummary && <p className="lead" data-motion-enter>{knowledge.shortSummary}</p>}{overview?.whatItIs && <Section title="What it is"><p>{overview.whatItIs}</p></Section>}{overview?.whatItDoes?.length ? <ItemSection title="What it does" items={overview.whatItDoes} /> : null}{knowledge.projectParts?.length ? <Section title="Main parts"><div className="project-part-list">{knowledge.projectParts.slice(0, 6).map((part) => <button key={part.id} type="button" onClick={() => onOpenPart(part)}><strong>{part.title}</strong><span>{part.shortExplanation}</span></button>)}</div></Section> : null}{overview?.whereToStart?.length ? <ItemSection title="Where to look first" items={overview.whereToStart} /> : null}{knowledge.technologies?.length ? <Section title="Built with"><div className="topic-list">{knowledge.technologies.map((technology) => <div key={technology.name}><h3>{technology.name}</h3>{technology.explanation && <p>{technology.explanation}</p>}<TechnicalName value={technology.technicalName} /></div>)}</div></Section> : null}{overview?.usefulContext && <p className="subtle" data-motion-enter>{overview.usefulContext}</p>}{knowledge.limitations && <TechnicalDisclosure section={knowledge.limitations} />}</article>
}

function Guide({ knowledge }: { knowledge: PresentationKnowledgeBase }) { const links = [['guide-brief', 'In brief', Boolean(knowledge.shortSummary)], ['guide-parts', 'Main parts', Boolean(knowledge.projectParts?.length)], ['guide-learning', 'Learning order', Boolean(knowledge.learningPath?.length)], ['guide-files', 'Files', Boolean(knowledge.files?.length)], ['guide-technical', 'Technical details', Boolean(knowledge.technicalReference?.length)]] as const; return <article className="guide"><p className="eyebrow">Complete Guide</p><h1>{knowledge.projectName}</h1><nav className="guide-contents" aria-label="Guide contents">{links.filter((link) => link[2]).map(([id, label]) => <a key={id} href={`#${id}`}>{label}</a>)}</nav>{knowledge.shortSummary && <Section id="guide-brief" title="In brief"><p>{knowledge.shortSummary}</p></Section>}{knowledge.projectParts?.length ? <Section id="guide-parts" title="Main parts"><div className="topic-list">{knowledge.projectParts.map((part) => <div key={part.id}><h3>{part.title}</h3><p>{part.shortExplanation}</p><TechnicalName value={part.technicalName} /></div>)}</div></Section> : null}{knowledge.learningPath?.length ? <Section id="guide-learning" title="A good learning order"><ItemSection title="" items={knowledge.learningPath} ordered /></Section> : null}{knowledge.files?.length ? <Section id="guide-files" title="Files"><FileList files={knowledge.files} /></Section> : null}{knowledge.technicalReference?.length ? <Section id="guide-technical" title="Technical details"><TechnicalDetails sections={knowledge.technicalReference} /></Section> : null}</article> }

function Parts({ knowledge, selected, onSelect }: { knowledge: PresentationKnowledgeBase; selected?: PresentationProjectPart; onSelect: (part: PresentationProjectPart) => void }) { return <article><p className="eyebrow">Project parts</p><h1>How the project is organised</h1><div className="part-tabs">{knowledge.projectParts?.map((part) => <button className={part.id === selected?.id ? 'active' : ''} key={part.id} type="button" onClick={() => onSelect(part)}>{part.title}</button>)}</div>{selected ? <PartDetail part={selected} /> : <p>No project part is available.</p>}</article> }

function PartDetail({ part }: { part: PresentationProjectPart }) { return <div className="part-detail"><h2>{part.title}</h2>{part.shortExplanation && <p className="lead">{part.shortExplanation}</p>}<TechnicalName value={part.technicalName} />{part.items?.length ? <ItemSection title="What is used here" items={part.items} /> : null}{part.relatedFiles?.length ? <Section title="Important files"><FilePaths paths={part.relatedFiles} /></Section> : null}{part.learningPath?.length ? <ItemSection title="What to learn first" items={part.learningPath} ordered /> : null}{part.essentialComplexity?.length ? <ItemSection title="What is essential" items={part.essentialComplexity} /> : null}{part.reviewBeforeCopying?.length ? <ItemSection title="Review before copying" items={part.reviewBeforeCopying} /> : null}<TechnicalDisclosure section={part} /></div> }

function Technologies({ knowledge }: { knowledge: PresentationKnowledgeBase }) { return <article><p className="eyebrow">Technologies</p><h1>What it is built with</h1><div className="topic-list">{knowledge.technologies?.map((technology) => <div key={technology.name}><h3>{technology.name}</h3>{technology.explanation && <p>{technology.explanation}</p>}<TechnicalName value={technology.technicalName} /><Evidence references={technology.evidenceReferences} /></div>)}</div></article> }
function Files({ knowledge }: { knowledge: PresentationKnowledgeBase }) { return <article><p className="eyebrow">Files</p><h1>Files in this project</h1><FileList files={knowledge.files ?? []} /></article> }
function Decisions({ knowledge }: { knowledge: PresentationKnowledgeBase }) { return <article><p className="eyebrow">Review before copying</p><h1>Choices worth reviewing</h1>{knowledge.projectParts?.flatMap((part) => part.reviewBeforeCopying?.map((item) => ({ ...item, part: part.title })) ?? []).map((item) => <div className="decision" key={`${item.part}-${item.id}`}><strong>{item.title}</strong><p>{item.explanation}</p><span className="review">{item.part}</span></div>)}</article> }

function ItemSection({ title, items, ordered = false }: { title: string; items: PresentationItem[]; ordered?: boolean }) { const content = items.map((item) => <div key={item.id}><h3>{item.title}</h3>{item.explanation && <p>{item.explanation}</p>}{item.whyItMatters && <p className="subtle">Why it matters: {item.whyItMatters}</p>}<TechnicalName value={item.technicalName} /><Evidence references={item.relatedEvidence} /></div>); return <Section title={title}>{ordered ? <ol className="learning-list">{items.map((item) => <li key={item.id}><strong>{item.title}</strong>{item.explanation && <span>{item.explanation}</span>}</li>)}</ol> : <div className="topic-list">{content}</div>}</Section> }
function FileList({ files }: { files: NonNullable<PresentationKnowledgeBase['files']> }) { return <div className="file-list">{files.map((file) => <div className="file-row" key={file.path}><code title={file.path}>{file.path}</code><span>{file.explanation ?? 'The file was found, but its exact role could not be confirmed.'}</span>{file.analysisStatus && file.analysisStatus !== 'analysed' && <em>{file.analysisStatus === 'uncertain' ? 'Role uncertain' : 'Partially inspected'}</em>}<TechnicalName value={file.technicalName} /></div>)}</div> }
function FilePaths({ paths }: { paths: string[] }) { return <div className="file-list">{paths.map((path) => <div className="file-row" key={path}><code>{path}</code></div>)}</div> }
function TechnicalName({ value }: { value?: string }) { return value ? <p className="subtle">Technical name: {value}</p> : null }
function Evidence({ references }: { references?: { path: string; fact?: string }[] }) { return references?.length ? <details className="disclosure"><summary>View technical evidence</summary><ul>{references.map((reference) => <li key={`${reference.path}-${reference.fact ?? ''}`}><code>{reference.path}</code>{reference.fact ? ` — ${reference.fact}` : ''}</li>)}</ul></details> : null }
function TechnicalDisclosure({ section }: { section: PresentationSection }) { return section.items?.length || section.evidenceReferences?.length || section.relatedFiles?.length || section.importRelationships?.length || section.codeExamples?.length ? <details className="disclosure"><summary>{section.id === 'analysis-notes' ? 'View analysis notes' : 'View technical details'}</summary>{section.shortExplanation && <p>{section.shortExplanation}</p>}{section.items?.length ? <div className="topic-list">{section.items.map((item) => <div key={item.id}><h3>{item.technicalName ?? item.title}</h3>{item.explanation && <p>{item.explanation}</p>}<Evidence references={item.relatedEvidence} /></div>)}</div> : null}{section.relatedFiles?.length ? <FilePaths paths={section.relatedFiles} /> : null}{section.importRelationships?.length ? <details className="disclosure"><summary>View import relationships</summary><ul>{section.importRelationships.map((relationship) => <li key={relationship}>{relationship}</li>)}</ul></details> : null}{section.codeExamples?.length ? <details className="disclosure"><summary>View code excerpt</summary>{section.codeExamples.map((example) => <pre key={example.label}><code>{example.code}</code></pre>)}</details> : null}<Evidence references={section.evidenceReferences} /></details> : null }
function TechnicalDetails({ sections }: { sections: PresentationSection[] }) { return <Section title="Technical details">{sections.map((section) => <TechnicalDisclosure key={section.id} section={section} />)}</Section> }
function Section({ title, children, id }: { title: string; children: ReactNode; id?: string }) { return <section className="content-section" id={id} data-motion-enter>{title && <h2>{title}</h2>}{children}</section> }
