import { useEffect, useRef, useState } from 'react'
import { acceptsLocalPath, classifyLocalPath, prepareLocalFiles } from '../project-sources/localFolderImport'
import type { LocalSkipReason } from '../project-sources/localFolderImport'
import { assessLocalProject } from '../project-sources/support'
import type { ProjectFile } from '../project-sources/types'
import type { CanonicalLauncherState } from './launcherState'

type DirectoryHandle = { name: string; values: () => AsyncIterableIterator<DirectoryHandle | FileSystemFileHandle>; kind: 'directory' }
type FileSystemFileHandle = { name: string; kind: 'file'; getFile: () => Promise<File> }
type FolderInput = HTMLInputElement & { webkitdirectory?: boolean }
async function read(handle: DirectoryHandle, prefix = ''): Promise<{ path: string; file: File }[]> { const files: { path: string; file: File }[] = []; for await (const child of handle.values()) { const next = `${prefix}${child.name}`; if (child.kind === 'directory') files.push(...await read(child as DirectoryHandle, `${next}/`)); else files.push({ path: next, file: await (child as FileSystemFileHandle).getFile() }) } return files }
async function prepare(entries: { path: string; file: File }[]) { const skippedByReason: Record<LocalSkipReason, number> = { 'dependency-generated': 0, sensitive: 0, 'binary-unsupported': 0, oversized: 0, unsafe: 0 }; const accepted: { path: string; content: string; size: number }[] = []; for (const entry of entries) { const reason = classifyLocalPath(entry.path, entry.file.size); if (!acceptsLocalPath(entry.path, entry.file.size)) { if (reason) skippedByReason[reason]++; continue } accepted.push({ path: entry.path, content: await entry.file.text(), size: entry.file.size }) } const result = prepareLocalFiles(accepted); return { ...result, skipped: result.skipped + Object.values(skippedByReason).reduce((a, b) => a + b, 0), skippedByReason: Object.fromEntries(Object.keys(skippedByReason).map((key) => [key, skippedByReason[key as LocalSkipReason] + result.skippedByReason[key as LocalSkipReason]])) as Record<LocalSkipReason, number> } }

interface Props { state: CanonicalLauncherState; enrichWithCodex: boolean; onEnrichWithCodex: (value: boolean) => void; onUsePrepared: () => void; onImportLocal: (name: string, files: ProjectFile[], summary: string, projectType: string, skipped: Record<LocalSkipReason, number>, support: 'supported' | 'too-large' | 'failed', diagnostics?: string[]) => void; onImportLocalPath: (path: string) => Promise<void>; onSourceReading: (value: boolean) => void; onAnalyse: () => void }
export function ReleaseLauncher({ state, enrichWithCodex, onEnrichWithCodex, onUsePrepared, onImportLocal, onImportLocalPath, onSourceReading, onAnalyse }: Props) {
  const input = useRef<FolderInput>(null); const [message, setMessage] = useState(''); const [reading, setReading] = useState(false); const [folderPath, setFolderPath] = useState(''); useEffect(() => { if (input.current) input.current.webkitdirectory = true }, [])
  const finish = (name: string, result: Awaited<ReturnType<typeof prepare>>) => { const assessment = assessLocalProject(result.files); const summary = `${result.files.length} relevant files`; setMessage(`${summary} · Import details`); onImportLocal(name, result.files, summary, assessment.projectType, result.skippedByReason, result.files.length ? 'supported' : assessment.support, assessment.evidence) }
  const choose = async () => { setReading(true); onSourceReading(true); try { const picker = (window as Window & { showDirectoryPicker?: () => Promise<DirectoryHandle> }).showDirectoryPicker; if (!picker) { input.current?.click(); return } const directory = await picker(); finish(directory.name, await prepare(await read(directory))) } catch (error) { if (error instanceof DOMException && error.name === 'AbortError') setMessage('Folder selection cancelled.'); else setMessage('The folder could not be prepared locally.') } finally { setReading(false); onSourceReading(false) } }
  const importPath = async () => { if (!folderPath.trim()) return; setReading(true); onSourceReading(true); try { await onImportLocalPath(folderPath); setMessage('Folder prepared locally.') } catch (error) { setMessage(error instanceof Error ? error.message : 'The folder could not be prepared locally.') } finally { setReading(false); onSourceReading(false) } }
  const source = state.source; const name = source?.kind === 'prepared' ? 'Prepared React/Vite sample' : source?.kind === 'local' ? source.name : undefined; const sourceMessage = source?.kind === 'local' ? source.summary ?? 'Project selected.' : source?.kind === 'prepared' ? 'Prepared React/Vite sample · ready to analyse' : 'No project selected yet.'
  return <main className="launcher-screen"><header className="launcher-header"><strong className="brand">Project Lens</strong></header><section className="launcher-stage"><div className="launcher-copy-block"><h1>Understand what was built.</h1><p className="launcher-copy">Choose a project and Project Lens will explain how it works.</p></div><div className="lens-launcher release-launcher"><p className="launcher-section-label">Project</p><button className="launcher-folder" type="button" onClick={() => void choose()} disabled={reading}><span className="folder-label">{name ?? 'Choose project folder'}</span><span>{reading ? 'Reading…' : 'Choose another folder'}</span></button><input ref={input} className="folder-input" type="file" multiple onChange={(event) => { const entries = [...(event.target.files ?? [])].map((file) => ({ path: file.webkitRelativePath || file.name, file })); event.target.value = ''; if (entries.length) void prepare(entries).then((result) => finish(entries[0].path.split('/')[0] || 'Local project', result)) }} /><label className="local-path-entry">Enter local folder path<input value={folderPath} onChange={(event) => setFolderPath(event.target.value)} placeholder="D:\\Projects\\my-app" onKeyDown={(event) => { if (event.key === 'Enter') void importPath() }} /></label><button className="link-sample" type="button" disabled={reading || !folderPath.trim()} onClick={() => void importPath()}>Open local path</button><button className="link-sample" type="button" onClick={onUsePrepared}>Try the prepared sample</button><p className="folder-status">{state.source?.projectType ?? sourceMessage}</p>{message && <p className="folder-status">{message}</p>}<div className="launcher-divider"/><p className="launcher-section-label">Codex enhancement</p><p className="ai-ready">{state.engine.status === 'ready' ? 'Codex ready to improve explanations' : 'Local analysis works without Codex'}</p><label className="folder-status"><input type="checkbox" checked={enrichWithCodex} onChange={(event) => onEnrichWithCodex(event.target.checked)} /> Add optional Codex explanations after the workspace opens</label><button className="launcher-analyse" type="button" disabled={!state.canAnalyse} onClick={onAnalyse}>Analyse project</button>{state.disabledReason && <p className="folder-status">{state.disabledReason}</p>}</div><p className="privacy-note">{state.privacyDescription}</p></section></main>
}
