import { useEffect, useRef, useState } from 'react'
import { acceptsLocalPath, classifyLocalPath, prepareLocalFiles } from '../project-sources/localFolderImport'
import type { LocalSkipReason } from '../project-sources/localFolderImport'
import { assessLocalProject } from '../project-sources/support'
import type { ProjectFile } from '../project-sources/types'
import type { CanonicalLauncherState, ModelChoice } from './launcherState'

type DirectoryHandle = { name: string; values: () => AsyncIterableIterator<DirectoryHandle | FileSystemFileHandle>; kind: 'directory' }; type FileSystemFileHandle = { name: string; kind: 'file'; getFile: () => Promise<File> }; type FolderInput = HTMLInputElement & { webkitdirectory?: boolean }
async function read(handle: DirectoryHandle, prefix = ''): Promise<{ path: string; file: File }[]> { const files: { path: string; file: File }[] = []; for await (const child of handle.values()) { const next = `${prefix}${child.name}`; if (child.kind === 'directory') files.push(...await read(child as DirectoryHandle, `${next}/`)); else files.push({ path: next, file: await (child as FileSystemFileHandle).getFile() }) } return files }
async function prepare(entries: { path: string; file: File }[]) { const accepted: { path: string; content: string; size: number }[] = []; for (const entry of entries) if (acceptsLocalPath(entry.path, entry.file.size)) accepted.push({ path: entry.path, content: await entry.file.text(), size: entry.file.size }); else classifyLocalPath(entry.path, entry.file.size); return prepareLocalFiles(accepted) }
interface Props { state: CanonicalLauncherState; models: string[]; model: ModelChoice; onModelChange: (value: ModelChoice) => void; enrichWithCodex: boolean; onEnrichWithCodex: (value: boolean) => void; onUsePrepared: () => void; onImportLocal: (name: string, files: ProjectFile[], summary: string, projectType: string, skipped: Record<LocalSkipReason, number>, support: 'supported' | 'too-large' | 'failed', diagnostics?: string[]) => void; onImportLocalPath: (path: string) => Promise<void>; onSourceReading: (value: boolean) => void; onAnalyse: () => void }
export function ReleaseLauncher({ state, models, model, onModelChange, onUsePrepared, onImportLocal, onSourceReading, onAnalyse }: Props) {
  const input = useRef<FolderInput>(null); const [reading, setReading] = useState(false); useEffect(() => { if (input.current) input.current.webkitdirectory = true }, [])
  const finish = (name: string, result: Awaited<ReturnType<typeof prepare>>) => { const assessment = assessLocalProject(result.files); onImportLocal(name, result.files, `${result.files.length} relevant files`, assessment.projectType, result.skippedByReason, result.files.length ? 'supported' : assessment.support, assessment.evidence) }
  const choose = async () => { setReading(true); onSourceReading(true); try { const picker = (window as Window & { showDirectoryPicker?: () => Promise<DirectoryHandle> }).showDirectoryPicker; if (!picker) { input.current?.click(); return } const directory = await picker(); finish(directory.name, await prepare(await read(directory))) } catch { /* cancellation is normal */ } finally { setReading(false); onSourceReading(false) } }
  const source = state.source; const name = source?.kind === 'prepared' ? 'Prepared React/Vite sample' : source?.kind === 'local' ? source.name : 'Choose project folder'; const friendly = (id: string) => id === 'gpt-5.4-mini' ? 'GPT-5.4 mini — Recommended' : id === 'gpt-5.4' ? 'GPT-5.4 — Higher capability' : id; const selected = models.includes(model ?? '') ? model : ''
  return <main className="launcher-screen"><header className="launcher-header"><strong className="brand">Project Lens</strong></header><section className="launcher-stage"><div className="launcher-copy-block"><h1>Understand what was built.</h1><p className="launcher-copy">Choose a project and Project Lens will explain how it works.</p></div><div className="lens-launcher release-launcher"><p className="launcher-section-label">Project</p><button className="launcher-folder" type="button" onClick={() => void choose()} disabled={reading}><span className="folder-label">{name}</span><span>{reading ? 'Reading…' : 'Change folder'}</span></button><input ref={input} className="folder-input" type="file" multiple onChange={(event) => { const entries = [...(event.target.files ?? [])].map((file) => ({ path: file.webkitRelativePath || file.name, file })); event.target.value = ''; if (entries.length) void prepare(entries).then((result) => finish(entries[0].path.split('/')[0] || 'Local project', result)) }} /><p className="folder-status">{source?.kind === 'local' ? source.summary : state.source?.projectType ?? 'No project selected yet.'}</p><div className="launcher-divider"/><p className="launcher-section-label">Model</p><label className="model-picker">Codex model<select value={selected} onChange={(event) => onModelChange(event.target.value || undefined)}><option value="">Choose a confirmed model</option>{models.map((id) => <option key={id} value={id}>{friendly(id)}</option>)}</select></label><p className="folder-status">Available models depend on your Codex account.</p><p className="ai-ready">Codex · {state.engine.status === 'ready' ? 'Ready' : state.engine.status}</p><button className="launcher-analyse" type="button" disabled={!state.canAnalyse} onClick={onAnalyse}>{selected ? `Analyse with ${selected}` : 'Choose a Codex model to continue'}</button><button className="link-sample" type="button" onClick={onUsePrepared}>Try the prepared sample</button>{state.disabledReason && <p className="folder-status">{state.disabledReason}</p>}</div><p className="privacy-note">{state.privacyDescription}</p></section></main>
}
