import { useEffect, useRef, useState } from 'react'
import { acceptsLocalPath, classifyLocalPath, prepareLocalFiles } from '../project-sources/localFolderImport'
import type { LocalSkipReason } from '../project-sources/localFolderImport'
import type { ProjectFile } from '../project-sources/types'
import type { LauncherSource } from './launcherState'

type DirectoryHandle = { name: string; values: () => AsyncIterableIterator<DirectoryHandle | FileSystemFileHandle>; kind: 'directory' }
type FileSystemFileHandle = { name: string; kind: 'file'; getFile: () => Promise<File> }
type FolderInput = HTMLInputElement & { webkitdirectory?: boolean }
async function fromDirectory(handle: DirectoryHandle, prefix = ''): Promise<{ path: string; file: File }[]> { const found: { path: string; file: File }[] = []; for await (const child of handle.values()) { const childPath = `${prefix}${child.name}`; if (child.kind === 'directory') found.push(...await fromDirectory(child as DirectoryHandle, `${childPath}/`)); else found.push({ path: childPath, file: await (child as FileSystemFileHandle).getFile() }) }; return found }
async function readLocalFiles(entries: { path: string; file: File }[]) { const skippedByReason: Record<LocalSkipReason, number> = { 'dependency-generated': 0, sensitive: 0, 'binary-unsupported': 0, oversized: 0, unsafe: 0 }; const candidates: { path: string; content: string; size: number }[] = []; for (const entry of entries) { const reason = classifyLocalPath(entry.path, entry.file.size); if (!acceptsLocalPath(entry.path, entry.file.size)) { if (reason) skippedByReason[reason]++; continue }; candidates.push({ path: entry.path, content: await entry.file.text(), size: entry.file.size }) }; const prepared = prepareLocalFiles(candidates); for (const key of Object.keys(skippedByReason) as LocalSkipReason[]) skippedByReason[key] += prepared.skippedByReason[key]; return { ...prepared, skipped: Object.values(skippedByReason).reduce((total, count) => total + count, 0), skippedByReason } }

interface Props { state: { source: LauncherSource; activeRuntime?: { displayName: string }; canAnalyse: boolean; disabledReason?: string; privacyDescription: string }; onUsePrepared: () => void; onImportLocal: (name: string, files: ProjectFile[], summary: string, skipped: Record<LocalSkipReason, number>) => void; onAnalyse: () => void }

export function ReleaseLauncher({ state, onUsePrepared, onImportLocal, onAnalyse }: Props) {
  const pickerRef = useRef<FolderInput>(null); const [status, setStatus] = useState(''); const [reading, setReading] = useState(false)
  useEffect(() => { if (pickerRef.current) pickerRef.current.webkitdirectory = true }, [])
  const finish = (name: string, prepared: Awaited<ReturnType<typeof readLocalFiles>>) => { if (!prepared.files.length) { setStatus('No supported project text files were found.'); return }; const summary = `${prepared.files.length} included · ${prepared.skipped} skipped`; setStatus(summary); onImportLocal(name, prepared.files, summary, prepared.skippedByReason) }
  const choose = async () => { setReading(true); try { const chooser = (window as Window & { showDirectoryPicker?: () => Promise<DirectoryHandle> }).showDirectoryPicker; if (!chooser) { pickerRef.current?.click(); return }; const directory = await chooser(); finish(directory.name, await readLocalFiles(await fromDirectory(directory))) } catch (error) { setStatus(error instanceof DOMException && error.name === 'AbortError' ? 'Folder selection cancelled.' : 'The folder could not be prepared locally.') } finally { setReading(false) } }
  const fallback = async (event: React.ChangeEvent<HTMLInputElement>) => { setReading(true); const entries = [...(event.target.files ?? [])].map((file) => ({ path: file.webkitRelativePath || file.name, file })); event.target.value = ''; if (entries.length) finish(entries[0].path.split('/')[0] || 'Local project', await readLocalFiles(entries)); else setStatus('Folder selection cancelled.'); setReading(false) }
  const sourceLabel = state.source?.kind === 'prepared' ? 'Prepared Vite sample' : state.source?.kind === 'local' ? `${state.source.name} · ${state.source.summary}` : undefined
  return <main className="launcher-screen"><header className="launcher-header"><strong className="brand">Project Lens</strong></header><section className="launcher-stage"><div className="launcher-copy-block"><h1>Understand what was built.</h1><p className="launcher-copy">Analyse a supported project with an AI coding engine you already use.</p></div><div className="lens-launcher" aria-label="Project launcher"><p className="launcher-section-label">Project source</p><button className="launcher-folder" type="button" aria-label="Choose project folder" onClick={() => void choose()}><span className="folder-label">Choose project folder</span></button><input ref={pickerRef} className="folder-input" type="file" multiple onChange={(event) => void fallback(event)} /><button className="link-sample" type="button" onClick={onUsePrepared}>Use prepared sample</button>{sourceLabel && <p className="folder-status" role="status">{sourceLabel}</p>}<p className="local-support">Local project analysis currently supports React and Vite projects.</p><div className="launcher-divider" /><p className="launcher-section-label">AI</p><p className="ai-ready">{state.activeRuntime ? `${state.activeRuntime.displayName} · Ready` : 'AI setup is required'}</p><button className="launcher-analyse" type="button" disabled={!state.canAnalyse || reading} onClick={onAnalyse}>{state.source?.kind === 'prepared' ? 'Analyse sample' : 'Analyse project'}</button>{(state.disabledReason || status) && <p className="folder-status" role="status">{state.disabledReason ?? status}</p>}</div><p className="privacy-note">{state.privacyDescription}</p></section></main>
}
