import { readdir, readFile } from 'node:fs/promises'
import path from 'node:path'
import { readRequiredArtifacts } from './codexCli'

type Finding = { runId: string; artifact: string; stage: string; status: 'pass' | 'block'; reason: string; recoverableLocally: boolean; suggestedCorrection?: string }
async function filesUnder(root: string) { const files: string[] = []; async function visit(current: string) { for (const entry of await readdir(current, { withFileTypes: true })) { const absolute = path.join(current, entry.name); if (entry.isDirectory()) await visit(absolute); else files.push(path.relative(root, absolute).replaceAll('\\', '/')) } } await visit(root); return files }
async function auditRun(runDirectory: string): Promise<Finding[]> {
  const runId = path.basename(runDirectory); const findings: Finding[] = []; const source = path.join(runDirectory, 'source'); const artifacts = path.join(runDirectory, 'artifacts'); const manifest = await filesUnder(source).catch(() => []); let state = 'unknown'
  try { state = (JSON.parse(await readFile(path.join(runDirectory, 'run.json'), 'utf8')) as { state?: string }).state ?? 'unknown' } catch { /* metadata finding below remains useful */ }
  findings.push({ runId, artifact: 'run.json', stage: 'metadata', status: 'pass', reason: 'Run directory and source snapshot found.', recoverableLocally: false })
  if (state === 'failed' || state === 'cancelled') { for (const name of ['overview.md', 'complete-guide.md']) findings.push({ runId, artifact: name, stage: 'terminal', status: 'pass', reason: `Run ended ${state}; generated artifacts are not expected.`, recoverableLocally: false }); return findings }
  for (const name of ['overview.md', 'complete-guide.md']) { const target = path.join(artifacts, name); try { const bytes = await readFile(target); const text = bytes.toString('utf8'); const visible = text.replace(/\s/g, '').length; findings.push({ runId, artifact: name, stage: 'encoding', status: visible ? 'pass' : 'block', reason: visible ? `UTF-8, ${bytes.length} bytes, ${text.split(/\r?\n/).length} lines.` : 'Artifact is empty.', recoverableLocally: !visible, suggestedCorrection: !visible ? 'Regenerate the artifact.' : undefined }) } catch (error) { findings.push({ runId, artifact: name, stage: 'file', status: 'block', reason: error instanceof Error ? error.message : 'Artifact could not be read.', recoverableLocally: false }) } }
  try { await readRequiredArtifacts(artifacts, new Set(manifest)); findings.push({ runId, artifact: 'overview.md + complete-guide.md', stage: 'validation', status: 'pass', reason: `Validated against ${manifest.length} source files.`, recoverableLocally: true }) } catch (error) { findings.push({ runId, artifact: 'overview.md + complete-guide.md', stage: 'validation', status: 'block', reason: error instanceof Error ? error.message : 'Validation failed.', recoverableLocally: true, suggestedCorrection: 'Recheck preserved artifacts locally.' }) }
  return findings
}
async function main() { const root = path.resolve(process.cwd(), '.project-lens', 'runs'); const runs = (await readdir(root, { withFileTypes: true }).catch(() => [])).filter((entry) => entry.isDirectory()); const findings = (await Promise.all(runs.map((run) => auditRun(path.join(root, run.name))))).flat(); if (process.argv.includes('--json')) console.log(JSON.stringify(findings, null, 2)); else console.table(findings.map(({ runId, artifact, stage, status, reason, recoverableLocally }) => ({ runId, artifact, stage, status, reason, recoverableLocally }))); if (findings.some((finding) => finding.status === 'block')) process.exitCode = 1 }
void main()
