const text = { type: 'string', maxLength: 500 }
const title = { type: 'string', minLength: 1, maxLength: 100 }
const evidence = { type: 'object', additionalProperties: false, required: ['path'], properties: { path: { type: 'string' }, fact: text } }
const item = { type: 'object', additionalProperties: false, required: ['id', 'title'], properties: { id: { type: 'string', minLength: 1 }, title, explanation: text, whyItMatters: text, technicalName: text, relatedEvidence: { type: 'array', items: evidence }, analysisStatus: { enum: ['analysed', 'inferred', 'detected', 'partial', 'unsupported', 'binary', 'skipped', 'generated', 'uncertain'] } } }
const section = { type: 'object', additionalProperties: false, required: ['id', 'title'], properties: { id: { type: 'string', minLength: 1 }, title, shortExplanation: text, items: { type: 'array', items: item }, technicalName: text, relatedFiles: { type: 'array', items: { type: 'string' } }, deeperExplanation: text, evidenceReferences: { type: 'array', items: evidence }, importRelationships: { type: 'array', items: text }, codeExamples: { type: 'array', items: { type: 'object', additionalProperties: false, required: ['label', 'code'], properties: { label: { type: 'string' }, code: { type: 'string', maxLength: 4000 } } } } } }
const part = { ...section, properties: { ...section.properties, learningPath: { type: 'array', items: item }, essentialComplexity: { type: 'array', items: item }, reviewBeforeCopying: { type: 'array', items: item } } }

export function createPresentationSchema() {
  return { $schema: 'https://json-schema.org/draft/2020-12/schema', type: 'object', additionalProperties: false, required: ['version', 'projectName'], properties: { version: { const: '1.0' }, projectName: { type: 'string', minLength: 1, maxLength: 100 }, projectTypeLabel: text, shortSummary: text, overview: { type: 'object', additionalProperties: false, properties: { whatItIs: text, whatItDoes: { type: 'array', items: item }, mainParts: { type: 'array', items: item }, whereToStart: { type: 'array', items: item }, usefulContext: text } }, sections: { type: 'array', items: section }, projectParts: { type: 'array', items: part }, files: { type: 'array', items: { type: 'object', additionalProperties: false, required: ['path'], properties: { path: { type: 'string' }, title: text, explanation: text, itemType: { type: 'string' }, technicalName: text, analysisStatus: { enum: ['analysed', 'inferred', 'detected', 'partial', 'unsupported', 'binary', 'skipped', 'generated', 'uncertain'] }, evidenceReferences: { type: 'array', items: evidence } } } }, technologies: { type: 'array', items: { type: 'object', additionalProperties: false, required: ['name'], properties: { name: title, explanation: text, technicalName: text, evidenceReferences: { type: 'array', items: evidence } } } }, learningPath: { type: 'array', items: item }, limitations: section, technicalReference: { type: 'array', items: section } } }
}
